#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HEADER_FILE="$ROOT_DIR/docs/readme-header.md"
OVERVIEW_FILE="$ROOT_DIR/SOLUTION_OVERVIEW.md"
OUT_FILE="$ROOT_DIR/README.md"

if [[ ! -f "$HEADER_FILE" ]]; then
  echo "Missing header file: $HEADER_FILE" >&2
  exit 1
fi

if [[ ! -f "$OVERVIEW_FILE" ]]; then
  echo "Missing solution overview file: $OVERVIEW_FILE" >&2
  exit 1
fi

{
  echo "<!-- AUTOGENERATED: run ./scripts/generate-readme.sh -->"
  cat "$HEADER_FILE"
  echo
  echo "---"
  echo
  echo "<!-- BEGIN: solution_overview -->"
  cat "$OVERVIEW_FILE"
  echo
  echo "<!-- END: solution_overview -->"
} > "$OUT_FILE"

echo "Generated $OUT_FILE from $HEADER_FILE + $OVERVIEW_FILE"
